### ISSUE TITLE
已star，请教一下大大如何拿到的 refresh_token？

### ISSUE THREAD

**Issue by chawaa** [Yanyutin753/refresh-gpt-chat#1]
大大，你好！如题，如何拿到的 refresh_token？有什么建议嘛？

还有一个小问题：配置 getAccessTokenUrl=http(s)://ip+port/url/auth/refresh_token 是否要写入自定义后缀？

先star，先感谢！

**Comment by Yanyutin753** [comment]
官网账号登录
直接使用地址:
https://chat.freegpts.org/
免翻，官网最新ui，支持team号，支持gpts
自己部署反代地址:https://freegpts.org/
——————
获取refreshCookie(session-token): https://chat.freegpts.org/getsession
获取refreshToken地址: https://chat.freegpts.org/applelogin
更多仓库请关注 https://github.com/xyhelper
——————
注:
1.蟑螂和freegpts为公益项目，免费没有付费项。

ninja作者推荐的https://chat.freegpts.org/applelogin，这个可以拿，在最下面

**Comment by Yanyutin753** [comment]
getaccesstokenurl 是把refresh_token转成access_token，用ninja的就能直接用

**Comment by chawaa** [comment]
抱拳感谢！

**Comment by chawaa** [comment]
大大，我进行了如下操作，项目还是没有跑通。

> ninja地址表示为：https://ninja.example.com
> refresh-gpt-chat地址表示为：https://refresh-gpt-chat.example.com

**1. https://chat.freegpts.org/applelogin 获取refreshToken，对应返回字段是refresh_token；**

**2. 搭建了refresh-gpt-chat项目，访问https://refresh-gpt-chat.example.com/自定义后缀 返回以下内容**
```
Thanks you use refresh-gpt-chat

[详细使用文档](https://apifox.com/apidoc/shared-4b9a7517-3f80-47a1-84fc-fcf78827a04a)

[项目地址](https://github.com/Yanyutin753/refresh-gpt-chat)
```
**3. 我refresh-gpt-chat 的 docker-compose.yml 配置文件如下**
```
version: '3'
services:
  refresh-gpt-chat:
    image: yangclivia/refresh-gpt-chat:latest
    # Java 的环境变量 （可适当调节，并发高可以适当调大点，具体可问gpt了解）
    environment:  
      - JAVA_OPTS=-XX:+UseParallelGC -Xms128m -Xmx128m -XX:MaxMetaspaceSize=128m  
    container_name: refresh-gpt-chat
    restart: always
    user: root
    network_mode: host
    pid: host
    privileged: true
    command:
      - --log=info
      - --server.port=8081
      - --server.servlet.context-path=/自定义后缀
      - --getAccessTokenUrl=https://refresh-gpt-chat.example.com/auth/refresh_token
      - --ninja_chatUrl=https://ninja.example.com/v1/chat/completions
```
**4. 搭建了ninja，并可以成功在 https://ninja.example.com/auth 获取access token**

**5. 成功搭建one api，并用官方key可以成功使用。**

**6. 在one api 配置refresh-gpt-chat 渠道如下**
```
渠道类型: openAI
渠道API地址: https://refresh-gpt-chat.example.com/自定义后缀/ninja
模型: gpt-3.5-turbo
密钥: x-vwrSavBRiK5FY09iyxxxxxx27UxxxxxxneGHT7CR （步骤1获取的refresh_token）
```
**7. 错误信息**
 - 在one api 上测试返回错误
```
错误：Error: invalid character 'r' looking for beginning of value Resp body: refresh_token is wrong
```
 - 在[ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web) 上测试 返回错误
```


访问密码不正确或为空，请前往[登录](/#/auth)页输入正确的访问密码，或者在[设置](/#/settings)页填入你自己的 OpenAI API Key。

```json
{
  "error": {
    "message": " (request id: 20240203105858212851830fDjUPt2s)",
    "type": "upstream_error",
    "param": "401",
    "code": "bad_response_status_code"
  }
}
```
**8. 为解决错误做了尝试**

在ninja的问题区，查找到了可能相关问题 https://github.com/gngpp/ninja/issues/504
**openai改对话协议了，返回的wss接口需要客户端去连接对话。**

请大大帮忙看看，再次谢谢。
